# Intro to Numpy

![](https://www.freecodecamp.org/espanol/news/content/images/2021/04/numpy-1-1-.png)

### ¿Qué es numpy?

Numpy es una biblioteca en Python que **permite realizar operaciones matemáticas avanzadas de forma eficiente** con estructuras de datos de alto rendimiento, principalmente **arrays**.

### ¿Por qué usar numpy?

Usar numpy sobre las listas de Python tiene una serie de ventajas como la **rapidez y la eficiencia** en operaciones matemáticas y de matriz. Además, numpy es una biblioteca muy popular y ampliamente utilizada en el campo de la **ciencia de datos** y el aprendizaje automático. **Es la base** de muchas otras bibliotecas de Python como **pandas, scikit-learn**...

### ¿Cómo instalar numpy?

Para instalar numpy, simplemente ejecuta el siguiente comando en tu terminal:

```bash
$ pip install numpy
```

## Conceptos Básicos de Numpy

A continuación, vamos a ver algunos conceptos básicos de numpy, primero debemos importar la librería:

In [1]:
# import numpy

import numpy as np

### Crear un array

Numpy gira en torno a un objeto llamado **`array`** que es una **matriz multidimensional de elementos del mismo tipo**. 

💡 Para crear un array, puedes usar la función **`np.array()`** y pasar una lista de elementos como argumento.

In [2]:
my_list = [1, 2]
my_array = np.array(my_list)
my_array

array([1, 2])

💡 También podemos crear arrays de ceros (`np.zeros()`), de unos (`np.ones()`), y con valores constantes específicos utilizando `np.full()`. 

In [3]:
my_array_with_zeros = np.zeros(5)  # 5 zeros
my_array_with_zeros
my_array_with_ones = np.ones(5)  # 5 ones
my_array_with_ones
my_array_with_sevens = np.full(5, 7)  # 5 sevens
my_array_with_sevens

array([7, 7, 7, 7, 7])

💡 Podemos crear secuencias de números consecutivos usando `np.arange()` o `np.linspace()`. También podemos crear arrays de números aleatorios usando `np.random.rand()`.

In [4]:
np.arange(5)  # 0, 1, 2, 3, 4
np.linspace(0, 2, 5)  # 0, 0.5, 1, 1.5, 2

array([0. , 0.5, 1. , 1.5, 2. ])

### El tipo de datos de un array

Recuerda que los arrays de numpy tienen un **tipo de datos** asociado. Puedes especificar el tipo de datos al crear un array o numpy intentará inferirlo automáticamente. Es muy importante tener en cuenta el tipo de datos de un array, ya que puede afectar a la precisión de los cálculos y al uso de la memoria. Los tipos principales son:

- **`int`**: Número entero
  - **`int8`**: Entero de 8 bits: -128 a 127
  - **`int16`**: Entero de 16 bits: -2^15 a 2^15-1
  - **`int32`**: Entero de 32 bits: -2^31 a 2^31-1
  - **`int64`**: Entero de 64 bits: -2^63 a 2^63-1
- **`float`**: Número con decimales (coma flotante)
  - **`float16`**: Número de coma flotante de 16 bits
  - **`float32`**: Número de coma flotante de 32 bits
  - **`float64`**: Número de coma flotante de 64 bits 
- **`bool`**: Booleano
- **`string`**: Cadena de texto
- **`object`**: Objeto de Python

Dentro de los `int` y `float`, también puedes especificar si quieres que sean **signed** o **unsigned**. Por ejemplo, `uint8` es un entero sin signo de 8 bits. Es decir, alberga valores de 0 a 255 (2^8-1). Un caso clásico de un array de tipo `uint8` es una imagen en escala de grises, donde cada píxel tiene un valor entre 0 y 255. El 0 representa el color negro y el 255 el blanco.

💡 En numpy podemos ver el tipo de un array usando el método `.dtype`

In [5]:
my_array_with_sevens.dtype

dtype('int64')

💡 También podemos cambiar el tipo de un array usando el método `.astype()`

In [6]:
my_array_with_sevens.astype(float).dtype

dtype('float64')

### La Forma de un Array (a.k.a. Shape)

La "forma" de un array en numpy es un concepto fundamental que **describe las dimensiones del array**. Se refiere al **número de elementos en cada dimensión** y se representa por una tupla de enteros. Cada número en esta tupla indica el tamaño del array en esa dimensión. Por ejemplo, un array de una dimensión (un vector) con 4 elementos tendría una forma de (4,), mientras que un array de dos dimensiones (una matriz) con 3 filas y 5 columnas tendría una forma de (3, 5).

![](https://pbs.twimg.com/media/FD1qSBqVgAg7078.jpg:large)

* Un **vector**, que es un array de una sola dimensión, podría tener una forma (n,) donde n es el número de elementos en el vector.
* Una **matriz**, que es un array de dos dimensiones, podría tener una forma (m, n) donde m es el número de filas y n el número de columnas.
* Un **tensor**, que es un array de tres dimensiones, a menudo utilizado en ciencias de datos para representar conjuntos de imágenes o datos espaciotemporales, podría tener una forma (p, m, n) donde p representa un conjunto de matrices de dimensiones m x n.

💡 La propiedad `.shape` de un objeto numpy array se puede utilizar para obtener la forma actual del array:

In [7]:
np.zeros((2, 6)).shape

(2, 6)

💡 Es posible modificar la forma de un array usando el método `.reshape()`.

In [8]:
my_matrix = np.zeros(6).reshape((2, 3))
my_matrix

array([[0., 0., 0.],
       [0., 0., 0.]])

💡 También podemos "aplanar" un array (convertirlo a un vector) usando `.flatten()`

In [9]:
my_matrix.flatten()  # from 2D to 1D

array([0., 0., 0., 0., 0., 0.])

## Operaciones Básicas

Podemos **sumar, restar, multiplicar y dividir** arrays de numpy de la misma forma que lo haríamos con números. ⚠️ Es importante tener en cuenta que estas operaciones se realizan **elemento a elemento**, por lo que **ambos arrays deben tener la misma forma.**

In [10]:
my_array_with_ones + 2  # array of 3s
my_array_with_ones - 2  # array of -1s
my_array_with_ones / 2  # array of 0.5s
my_array_with_ones * 2  # array of 2s

array([2., 2., 2., 2., 2.])

💡 También podemos aplicar funciones matemáticas a un array de numpy, como **`np.sin()`, `np.cos()`, `np.exp()`, `np.log()`**...

In [11]:
my_array = np.arange(3)
np.cos(my_array)

array([ 1.        ,  0.54030231, -0.41614684])

## Agregación y Estadísticas

Numpy proporciona una serie de funciones para realizar **operaciones de agregación y estadísticas** en arrays. Algunas de las más comunes son:

- **`np.sum()`**: Suma de todos los elementos del array
- **`np.mean()`**: Media de los elementos del array
- **`np.median()`**: Mediana de los elementos del array
- **`np.min()`**: Valor mínimo del array
- **`np.max()`**: Valor máximo del array

In [12]:
my_array = np.arange(5)
my_array += 7
my_array

array([ 7,  8,  9, 10, 11])

In [13]:
np.sum(my_array)  # 45
np.median(my_array)  # 9.0
np.max(my_array)  # 11
np.min(my_array)  # 7

7

💡 También podemos calcular la posición del elemento máximo usando **`np.argmax()`** o **`np.argmin()`**

In [14]:
np.argmax(my_array)  # 4
np.argmin(my_array)  # 0

0

## Array Slicing

Al igual que en las listas de Python, podemos **acceder a elementos individuales o a subconjuntos de elementos** en un array de numpy utilizando la técnica de **slicing**. Para ello, podemos utilizar la notación de corchetes y dos puntos `:`.

In [15]:
my_matrix = np.arange(16).reshape((4, 4))
my_matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
# tomamos las primeras dos filas y las primeras tres columnas
my_matrix[:2, :3]

array([[0, 1, 2],
       [4, 5, 6]])

## Array Masking

El **enmascaramiento de arrays** es una técnica que nos permite **filtrar** los elementos de un array basándonos en una **condición lógica**. Por ejemplo, podemos seleccionar todos los elementos de un array que sean mayores que un cierto valor, o que cumplan una determinada condición. Esto será especialmente útil cuando trabajemos con tablas de datos y queramos filtrar filas o columnas basándonos en ciertas condiciones.

In [17]:
ages = np.arange(8) + 15
ages

array([15, 16, 17, 18, 19, 20, 21, 22])

In [18]:
mask = ages >= 18
mask

array([False, False, False,  True,  True,  True,  True,  True])

Para crear un array nuevo aplicando un condicional puedo usar `np.where()`.

In [19]:
np.where(mask, ages, 0)

array([ 0,  0,  0, 18, 19, 20, 21, 22])

## 💪 Ejercicios

A continuación, te propongo algunos ejercicios para que practiques tus habilidades con numpy

### Ejercicio I: The Alien Invasion

El ejercicio original puede encontrarse [aquí](https://matesanz.github.io/python-machine-learning-course/%F0%9F%A7%AA-Exercises/the-alien-invasion/).


The transmission is an matrix (an array) which contains data for each spaceship. Every line represents one spaceship, with values in the order of: length (in meters), width (in meters), height (in meters), speed (in km/s), and weapon power (on a scale of 1-10).

In [1]:
import numpy as np


fleet_data = np.array([
    [120, 40, 25, 2.5, 10],
    [85, 60, 30, 5.0, 5],
    [100, 50, 35, 4.5, 7],
    [120, 40, 25, 2.5, 9],
    [150, 50, 30, 3.0, 10],
], dtype=np.float32)

In [2]:
# Calculate and print the total number of spaceships.

fleet_length = fleet_data.shape[0]
fleet_length = len(fleet_data)
f"Total number of spaceships: {fleet_length}"

'Total number of spaceships: 5'

In [3]:
# Calculate and print the average spaceship size (volume).

lengths = fleet_data[:, 0]
lengths
widths = fleet_data[:, 1]
widths
heights = fleet_data[:, 2]
heights

volumes = lengths * widths * heights
mean_volume = np.mean(volumes)
f"Average spaceship volume: {mean_volume} m3"

'Average spaceship volume: 158600.0 m3'

In [4]:
# Identify and print the speed of the fastest spaceship.

speeds = fleet_data[:, 3]
max_speed = np.max(speeds)

f"Speed of the fastest spaceship: {max_speed} km/s"

'Speed of the fastest spaceship: 5.0 km/s'

In [5]:
# Determine and print the number of spaceships with the maximum weapon power.

weapon_power = fleet_data[:, 4]
max_power_mask = weapon_power == 10
ships_with_max_power = fleet_data[max_power_mask]
n_spaceships_with_max_power = len(ships_with_max_power)
f"Number of spaceships with the maximum weapon power: {n_spaceships_with_max_power}"

'Number of spaceships with the maximum weapon power: 2'

In [6]:
# Find and print the mean speed of spaceships with the maximum weapon power.

speeds_of_ships_with_max_power = speeds[max_power_mask]
mean_speed_of_ships_with_max_power = np.mean(speeds_of_ships_with_max_power)
f"Mean speed of spaceships with the maximum weapon power: {mean_speed_of_ships_with_max_power} km/s"

'Mean speed of spaceships with the maximum weapon power: 2.75 km/s'

### Ejercicio II: Crea un Tres en Raya

To try out your new skills, try to create a TicTacToe game using Numpy arrays. Fill the functions below to create a game that can be played by two players.

In [12]:
board = np.zeros((3,3))
board [1,2] =3
board [0,0] =1
board

array([[1., 0., 0.],
       [0., 0., 3.],
       [0., 0., 0.]])